config/routes.rb
Public::Application.routes.draw do

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :invitations => 'users/invitations'
  }

  unauthenticated do
    root 'welcome#index'
  end

  authenticated :user do
    root 'discussions#index', as: 'authenticated_root'
  end

  get "about" => 'welcome#about'
  get "team" => 'welcome#team'
  get "contact" => 'welcome#contact'
  post "contact" => 'welcome#message'
  get "blog" => 'welcome#blog'
  get "features" => 'welcome#features'
  get "pricing" => 'welcome#pricing'
  get "terms" => 'welcome#terms'
  get "privacy" => 'welcome#privacy'
  post "newsletter" => 'welcome#newsletter'

  get 'settings' => 'settings#show'
  put 'settings' => 'settings#update'

  get 'p/n/:token' => 'public#show', as: 'public_note'

  resource :incoming, :controller => 'incoming', :only => [:show,:create]

  resources :discussions do
    resources :notes
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def team
  end

  def contact
  end

  def message
    email = params['email']

    Intercom::User.create(:email => email, :created_at => Time.now())
    Intercom::Tag.create(:name => 'Contact', :emails => [email], :tag_or_untag => 'tag')

    begin
      message = {
        :subject=> "Contact for TeamStatus.TV",
        :text=>"Contact from:\nName: #{params['name']}\nEmail: #{params['email']}\n\n#{params['message']}",
        :from_name=> "TeamStatus.TV",
        :from_email=> "root@remotestandup.com",
        :to=>[
          {:email => "pawel@remotestandup.com", :name => "Pawel Niewiadomski"}
        ]
      }
      mandrill.messages.send message
    rescue Mandrill::Error => e
      logger.error("A mandrill error occurred: #{e.class} - #{e.message}")
      raise e
    end

    return_status_accepted
  end

  def blog
    redirect_to 'http://blog.teamstatus.tv'
  end

  def features
  end

  def pricing
  end

  def privacy
  end

  def terms
  end

  def newsletter
    email = params['email']

    begin
      # Intercom::User.create(:email => email, :created_at => Time.now())
      # Intercom::Tag.create(:name => 'Newsletter', :emails => [email], :tag_or_untag => 'tag')

      list = mailchimp.lists.list({:filters => {:list_name => ENV['MAILCHIMP_LIST']}})
      raise "Unable to retrieve list id from MailChimp API." if list.nil? or list["status"] == "error"
      raise "List not found from MailChimp API." if list["total"].to_i != 1

      # http://apidocs.mailchimp.com/api/rtfm/listsubscribe.func.php
      # double_optin, update_existing, replace_interests, send_welcome are all true by default (change as desired)
      status = mailchimp.lists.subscribe({:id => list["data"][0]["id"], :email => {:email => email}, :double_optin => false})
      raise "Communication problem" if status.nil?
      raise "Unable to add #{email} to list from MailChimp API." if status["status"] == "error" and status["name"] != "List_AlreadySubscribed"
    rescue Exception => error
      logger.error "Error adding a subscriber #{error}"
      raise error
    end

    return_status_accepted
  end

  private

  def mailchimp
    @gibbon ||= Gibbon::API.new(ENV['MAILCHIMP_KEY'])
    @gibbon.throws_exceptions = false
    return @gibbon
  end

  def mandrill
    if (ENV['MANDRILL_KEY'])
      @mandrill ||= ::Mandrill::API.new ENV['MANDRILL_KEY']
    end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper

	def resource_name
    :user
  end

  def resource_class
  	User
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/views/welcome/_navigation.html.haml
/
  Change order for full width navbar
  <div class="navbar">
  <div class="container" data-toggle="clingify">
.container{"data-toggle" => "clingify"}
  .navbar
    /
      mobile collapse menu button
      \- data-toggle="toggle" = default BS menu
      \- data-toggle="jpanel-menu" = jPanel Menu
    %a.navbar-btn{"data-target" => ".navbar-collapse", "data-toggle" => "jpanel-menu"}
      %span.bar
      %span.bar
      %span.bar
      %span.bar
    / user menu
    .btn-group.user-menu.pull-right
      %a.btn.btn-primary.signup{"data-toggle" => "modal", href: "#signup-modal"} Sign Up
      / %a.btn.btn-primary.dropdown-toggle.login{"data-toggle" => "modal", href: "#login-modal"} Login
      %a.btn.btn-primary.dropdown-toggle.login{href: url_for(:controller => 'login', :action => 'google')} Login
    / everything within this div is collapsed on mobile
    .navbar-collapse.collapse
      / main navigation
      %ul.nav.navbar-nav
        %li.home-link
          =link_to root_path do
            %i.fa.fa-home
            %span.hidden Home
        %li{:class => ('active' if current_page? pricing_path)}
          %a.menu-item{href: pricing_path} Pricing
        %li.dropdown{:class => ('active' if current_page? about_path or current_page? team_path or current_page? contact_path)}
          %a#about-drop.dropdown-toggle{"data-toggle" => "dropdown", href: about_path} About +
          / Dropdown Menu
          %ul.dropdown-menu{"aria-labelledby" => "about-drop", role: "menu"}
            %li{role: "presentation"}
              %a.menu-item{href: about_path, role: "menuitem", tabindex: "-1"} About Us
            %li{role: "presentation"}
              %a.menu-item{href: team_path, role: "menuitem", tabindex: "-1"} Our Team
            %li{role: "presentation"}
              %a.menu-item{href: contact_path, role: "menuitem", tabindex: "-1"} Contact
        %li{:class => ('active' if current_page? blog_path)}
          %a.menu-item{href: blog_path} Blog

app/views/welcome/about.html.haml
.row
  =render :partial => 'about_sidebar'

  / main content
  .col-md-9
    %h2.title-divider
      %span
        About
        %span.de-em Us
      %small What &amp; who makes us tick!
    / About company
    %h4 How It All Began
    %p We've built it because there was no other tool that could match our expectations. Working remotely is part of our life and we're obsessed with improving our communication. We've often asked ourselves "what have I accomplished today?". There's so many tools that we use on a day to day basis, so why not to use them to help us give an answer?

    %h4 Our Philosophy
    %p Rules we follow.
    %p
      %span.em Don't fuck the customer
      It's all about helping people succeed. We put customers first, because we are passionate about helping them achieve their goals. There's nothing better than knowing that you actually helped someone.
    %p
      %span.em Think globally, act locally
      Think about the bigger picture, keep it in mind, but also be aware of all the constraints, do the best possible job you can do at this moment in time that will bring you forward to the bigger goal, but try not to reach the bigger goal in one jump. It's unreasonable and you don't know where the journey will actually take you. By making small steps you discover all the details behind the bigger goal.
    %p
      %span.em You are responsible
      You are in charge, no one else can tell you what to do and no one else will take blame for you. You create your own roadmap, you set your own goals, you set your own work time. And if you fail it's only because of you. But don't worry failures are the best way to learn new things and grow!
    %p
      %span.em Be the change you seek
      If you noticed there are no managers here. There's no hierarchy. No one's telling you what to do. So if you see something is broken it's your job to fix it, go spend your time and improve it.
    %p
      %span.em Steal like an artist
      You should not be ashamed of copying ideas. All great inventions start with someone taking an idea, improving it, building upon it and shipping it. Steal so the artist you stole it from can say only "wow, that's amazing, I wish I thought of that"!
    %p
      %span.em Have fun
      Life's an adventure, so treat your job like an adventure too! Work on fun stuff, cool projects, do whatever makes you happy. Remember that sometimes a boring job can be an adventure for someone else, and other way around. So don't be ashamed and don't treat it as your duty to do the boring stuff. Find someone that will take pleasure from it, or find a way to outsource it.

    / =render :partial => 'vital_stats'

    / =render :partial => 'testimonials2'

app/views/welcome/contact.html.haml
.row
  =render :partial => 'about_sidebar'

  / main content
  .col-md-9
    %h2.title-divider
      %span
        Contact
        %span.de-em Us
      %small Ways To Get In Touch
    .row
      .col-md-6
        %form#contact-form{action: "#", role: "form", name: 'contact', :'ng-app' => 'teamstatus.public.contact', :'ng-controller' => 'ContactCtrl', 'ng-submit' => 'sendMessage()'}
          .alert.alert-success{:'ng-show' => 'succeeded', 'ng-cloak' => ''} Message was sent. Thank you!
          .form-group
            %label.sr-only{for: "contact-name"} Name
            %input#contact-name.form-control{placeholder: "Name", type: "text", name: 'name', :'ng-model' => 'name', :'ng-disabled' => 'loading'}/
          .form-group
            %label.sr-only{for: "contact-email"} Email
            %input#contact-email.form-control{placeholder: "Email", type: "email", name: 'email', required: true, :'ng-model' => 'email', 'ng-minlength' => "5", :'ng-disabled' => 'loading'}/

            %small.error{"ng-show" => "contact.email.$error.email"} That's not a valid email
            %small.error{"ng-show" => "contact.email.$error.minlength"} Email is required to be at least 5 characters
            %small.error{"ng-show" => "contact.email.$error.required"} Email is required

          .form-group
            %label.sr-only{for: "contact-message"} Message
            %textarea#contact-message.form-control{placeholder: "Message", rows: "12", name: 'message', required: true, :'ng-model' => 'message', 'ng-minlength' => '5', :'ng-disabled' => 'loading'}

            %small.error{"ng-show" => "contact.message.$error.minlength"} Message is required to be at least 5 characters
            %small.error{"ng-show" => "contact.message.$error.required"} Message is required

          %input.btn.btn-primary{type: "submit", value: "Send Message", :'ng-disabled' => 'loading', :'ng-hide' => 'loading'}/
          %input.btn.btn-primary{type: "submit", value: "Sending...", :'ng-disabled' => 'loading', :'ng-show' => 'loading'}/
      .col-md-6
        %p
          %abbr{title: "Phone"}
            %i.fa.fa-phone
          %a{href: contact_phone_url}=contact_phone
        %p
          %abbr{title: "Email"}
            %i.fa.fa-envelope
          %a{href: 'mailto:' + contact_email}=contact_email
        %p
          %abbr{title: "Address"}
            %i.fa.fa-home
          Tischnera 14. Gdansk. Poland. 80-283.
        / %p
        /   %a{href: "https://maps.google.co.uk/maps?q=&ie=UTF8&hq=&hnear=London,+United+Kingdom&gl=uk&t=m&ll=51.510238,-0.127029&spn=0.042735,0.102654&z=12&"}
        /     %img.img-thumbnail{alt: "Location map", src: image_path("misc/map.png")}/

app/views/welcome/features.html.haml
/ Services
.block.features
  %h2.title-divider
    %span
      Core
      %span.de-em Features
    %small Core features included in all plans.
  .row.list-unstyled
    =render :partial => 'main_features'
  .row
    / Secondary features
    .col-md-9
      %h3.title-divider
        %span
          Widgets
          %span.de-em Gallery
        %small Widgets available currently.
      .tabbable.tabs-left.vertical-tabs.bold-tabs.row
        %ul.nav.nav-tabs.nav-stacked.col-sm-4.col-md-4
          %li.active
            %a{"data-toggle" => "tab", href: "#tab1"}
              JIRA
              %small Watch your progress
              %i.fa.fa-angle-right
          %li
            %a{"data-toggle" => "tab", href: "#tab2"}
              Crucible
              %small Reviews in progress
              %i.fa.fa-angle-right
          %li
            %a{"data-toggle" => "tab", href: "#tab3"}
              Bamboo
              %small Monitor your builds
              %i.fa.fa-angle-right
          %li
            %a{"data-toggle" => "tab", href: "#tab4"}
              PostgreSQL
              %small Your custom data
              %i.fa.fa-angle-right
          %li
            %a{"data-toggle" => "tab", href: "#tab5"}
              Clock
              %small Time around the world
              %i.fa.fa-angle-right
          %li
            %a{"data-toggle" => "tab", href: "#tab6"}
              STFU
              %small Tell your team to be quiet
              %i.fa.fa-angle-right

        .tab-content.col-sm-8.col-md-8

          #tab1.feature.tab-pane.active.col-sm-12.col-md-12
            %img.img-responsive{alt: "JIRA", src: image_path('feature-jira.png')}/
            %h3.title.visible-phone Watch your progress
            / only show on mobile when tabs are open
            %p Connect to JIRA and watch your progress.

          #tab2.feature.tab-pane.col-sm-12.col-md-12
            %img.img-responsive{alt: "Crucible", src: image_path("features/feature-2.png")}/
            %h3.title.visible-phone Reviews in progress
            / only show on mobile when tabs are open
            %p Connect to Crucible and monitor review progress in your team.

          #tab3.feature.tab-pane.col-sm-12.col-md-12
            %img.img-responsive{alt: "Bamboo", src: image_path('feature-bamboo.png')}/
            %h3.title.visible-phone Monitor your builds
            / only show on mobile when tabs are open
            %p Connect to Bamboo and monitor your builds.

          #tab4.feature.tab-pane.col-sm-12.col-md-12
            %img.img-responsive{alt: "PostgreSQL", src: image_path('feature-postgresql.png')}/
            %h3.title.visible-phone Your custom data
            / only show on mobile when tabs are open
            %p Connect to PostgreSQL and display custom data.

          #tab5.feature.tab-pane.col-sm-12.col-md-12
            %img.img-responsive{alt: "Clock", src: image_path('feature-clock.png')}/
            %h3.title.visible-phone Clock
            / only show on mobile when tabs are open
            %p Show time around the world.

          #tab6.feature.tab-pane.col-sm-12.col-md-12
            %img.img-responsive{alt: "STFU", src: image_path('feature-stfu.png')}/
            %h3.title.visible-phone STFU
            / only show on mobile when tabs are open
            %p Tell your team to be quiet.

    / Contact block
    .col-md-3
      %h3.title-divider
        %span Questions?
        %small Get in touch!
      %p
        %abbr{title: "Phone"}
          %i.fa.fa-phone
        %a{href: contact_phone_url}=contact_phone
      %p
        %abbr{title: "Email"}
          %i.fa.fa-envelope
        %a{href: 'mailto:' + contact_email}=contact_email
      %p
        %abbr{title: "Address"}
          %i.fa.fa-home
        %span.nowrap Tischnera 14. Gdansk.
        %span.nowrap Poland. 80-283.

app/views/welcome/index.html.haml
#highlighted
  .inner
    / Static Banner
    %section.static-banner.container
      .slide
        .col-md-7
          %h2 Track your progress!
          %h2
            %small Respond to a daily email reminder with what you did that day.
          %h2
            %small Next day get an update from your team.
          %h2
            %small Cannot be simpler.

        .col-md-5.caption
          = form_for(resource, :as => resource_name, :url => registration_path(resource_name), html: {:role => 'form'}) do |f|
            = devise_error_messages!
            .form-group
              = f.label :email
              %br/
              = f.email_field :email, class: 'form-control'
            .form-group
              = f.label :password
              %br/
              = f.password_field :password, class: 'form-control'
            %div= f.submit "Sign up", class: 'btn btn-primary'

#content
  .container
    .block
      %h2.title-divider
        %span
          The easiest,
          %span.de-em friendliest way to manage your team

      .row
        .col-md-6
          %h5
            Track
            %span.de-em what's going on

          %p Either when you work remotely or in one place you often find it hard to track the things you do daily to move forward.

          %p We will remind your whole team to communicate and report their progrees so you don't loose track.

        .col-md-6
          %h5
            Report
            %span.de-em progress

          %p It's easier to report you status to stakeholders if you have a history of your team's achievements.

          %p Be always prepared to tell what's going on in your team and project.
      .row
        .col-md-6
          %h5
            You
            %span.de-em already know it

          %p Based on your habit of replying to email you don't have to change your workflow.

          %p If you know how to write and read email, so you already know how to use RemoteStandup.

        .col-md-6
          %h5
            Remember
            %span.de-em what you did

          %p Make performance reviews a story of the past. By tracking your accomplishements and problems daily you can easily discover areas for improvement.

          %p Help yourself understand how much of a progress you did. See a bigger picture from a time perspective and be proud of what you accomplished.

    / Services
    / .block.features
    /   %h2.title-divider
    /     %span
    /       Core
    /       %span.de-em Features
    /     / %small Core features included in all plans.
    /   .row
    /     =render :partial => 'main_features'

    / =render :partial => 'testimonials'

app/views/welcome/pricing.html.haml
.block
  / Default Pricing Table
  %h2.title-divider
    %span
      Our
      %span.de-em pricing
    %small Sign up in 20 seconds!
  / Stack 1
  .row.pricing-stack
    .col-md-6.col-md-offset-3
      .well.active
        %h3.title
          %span.em Plain and simple pricing
        %p.price
          %span.currency $
          %span.digits
            3
          %span.term PER USER MONTHLY
        %ul.unstyled.points
          %li SSL encrypted connections
          %li Unlimited number of updates
          %li Cancel any time
          %li Free for single user
  .row
    / Plan features
    .well.well-mini.pull-center
      %h4.inline-el.pad-right
        %span
          Try it for FREE
          = succeed ":" do
            %span.de-em for 30 days
      %p.inline-el.pad-left.muted
        %a.btn.btn-primary{href: new_user_registration_path} Try it now!
        %p Additionally VAT will be added if applies

app/views/welcome/privacy.html.haml
.row
  =render :partial => 'about_sidebar'

  / main content
  .col-md-9
    %h2.title-divider
      %span
        Our
        %span.de-em privacy policy
      %small What happens to your data!

    %h4 Information we collect
    %p
      We collect data about you from a variety of sources, including:

      %ul
        %li Information you provide to us directly;
        %li Information we collect in connection with your use of TeamStatus Services; and
        %li Information we collect from integrations with third-party products, such as Google Apps.

      All of the information we collect may be combined to help us tailor our communications to you and to develop and improve our services.

    %h4 How We Use Your Information
    %p
      We use the information we collect to:

      %ul
        %li Provide the services you request;
        %li Communicate with you, including customer support;
        %li Report anonymized, aggregate usage statistics;
        %li Deliver marketing and other offers or information related to TeamStatus Services; and
        %li Improve TeamStatus Services.

    %h4 How We Share and Disclose Your Information
    %p
      We do not share your Personal Information with other people or nonaffiliated companies for their marketing purposes (including direct marketing purposes). We may use and share Non-Personal Information for our marketing purposes including to display advertisements on other websites. We may share information:

    %ul
      %li With our third-party service suppliers and vendors;
      %li If TeamStatus is merged or sold to another company;
      %li To protect and defend the rights and property of TeamStatus (including enforcing our End User Agreement); and
      %li When required by law.

app/views/welcome/team.html.haml
.row
  =render :partial => 'about_sidebar'

  / main content
  .col-md-9
    %h2.title-divider
      %span
        The
        %span.de-em Team
      %small
        Our team of stars!
    / The team
    #team.block.team.margin-top-large
      .media
        .pull-left
          %img.img-thumbnail.media-object{alt: "Pawel Niewiadomski", src: image_path('pawel-niewiadomski.jpeg')}/
        .media-body
          %h4.media-heading Pawel Niewiadomski
          %p.role Founder &amp; Developer
          %p
            Be bold. Question the status quo. Be creative. Less is better. Live a moment. Help others. Focus. Ignore everybody. Think differently. Become a linchpin. Fail often. Stay hungry. Stay foolish.
          %ul.list-inline
            %li
              %a{href: "https://twitter.com/devonsteroids"}
                %i.fa.fa-twitter
                Twitter
            %li
              %a{href: "https://www.facebook.com/pawelniewie"}
                %i.fa.fa-facebook
                Facebook
            %li
              %a{href: "http://linkedin.com/in/pawelniewiadomski"}
                %i.fa.fa-linkedin
                LinkedIn
            %li
              %a{href: "https://plus.google.com/u/0/110326854159605514630/posts"}
                %i.fa.fa-google-plus
                Google+
      .media
        .pull-left
          %img.img-thumbnail.media-object{alt: "Jan Nowak", src: image_path('jan-nowak.jpg')}/
        .media-body
          %h4.media-heading Jan Nowak
          %p.role Founder &amp; Biz Dev
          %p Work smart. Don't waste your time on doing stupid things. Always look for opportunities in change. Don't be afraid to do anything. It's ok to try everything in life. Travel a lot.

          %ul.list-inline
            %li
              %a{href: "http://twitter.com/yohnyyN"}
                %i.fa.fa-twitter
                Twitter
            %li
              %a{href: "https://www.facebook.com/jan.nowak.9484"}
                %i.fa.fa-facebook
                Facebook
            %li
              %a{href: "https://linkedin.com/pub/jan-nowak/68/9bb/290"}
                %i.fa.fa-linkedin
                LinkedIn
      .media
        .pull-left
          %img.img-thumbnail.media-object{alt: "Robert", src: image_path("team/deniro.jpg")}/
        .media-body
          %h4.media-heading This is place for you!
          %p.role Can you help us?
          %p
            If you feel you can help and you believe you would be a good fit for our team please wait no more and shoot us
            =succeed '.' do
              %a{href: 'mailto:job@remotestandup.com'} an email

    / =render :partial => 'testimonials3'

app/views/welcome/terms.html.haml
.row
  =render :partial => 'about_sidebar'

  / main content
  .col-md-9
    %h2.title-divider
      %span
        Your
        %span.de-em terms of use
      %small What we think you will use TeamStatus for!
    / About company
    %h4 Lawyers dispatched!
    %p Hopefully they will return with something understandable by mere mortals.